---
- include_tasks: storage/glusterfs.yml
  when:
  - openshift_hosted_registry_storage_kind | default(none) == 'glusterfs' or openshift_hosted_registry_storage_glusterfs_swap

- include_tasks: storage/hostpath.yml
  when:
  - openshift_hosted_registry_storage_kind | default(none) in ['hostpath']
