---
# This file is looped over, must use include_tasks, not import_tasks
- include_tasks: fetch_config.yml

- fail:
    msg: "Configmap for {{ l_openshift_node_group_name }} must be present"
  when: configout.results.results.0 == {}
